name: Cross-repository compatibility
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  compatibility:
    uses: cubacadabra/tools/.github/workflows/compatibility-reusable.yml@main
    with:
      studio_ref: ${{ github.sha }}
